enum NeriDimen {
  railWidth,
  listPaneWidth,
  controlSize,
  avatarXs,
  avatarSm,
  avatarMd,
  avatarLg,
  mentionAvatar,
  mentionIcon,
  iconSm,
  iconMd,
  emojiSm,
  emojiLg,
  fadeHeight,
  replyHeight,
  channelHeaderHeight,
  dialogWidth,
  attachmentCard,
}

const neriDimentDefaults = <NeriDimen, double>{
  NeriDimen.railWidth: 76,
  NeriDimen.listPaneWidth: 310,
  NeriDimen.controlSize: 40,
  NeriDimen.avatarXs: 20,
  NeriDimen.avatarSm: 45,
  NeriDimen.avatarMd: 58,
  NeriDimen.avatarLg: 73,
  NeriDimen.mentionAvatar: 16,
  NeriDimen.mentionIcon: 14,
  NeriDimen.iconSm: 24,
  NeriDimen.iconMd: 30,
  NeriDimen.emojiSm: 20,
  NeriDimen.emojiLg: 48,
  NeriDimen.fadeHeight: 31,
  NeriDimen.replyHeight: 26,
  NeriDimen.channelHeaderHeight: 57,
  NeriDimen.dialogWidth: 360,
  NeriDimen.attachmentCard: 100,
};
