enum NeriDimen {
  railWidth,
  listPaneWidth,
  controlSize,
  avatarXs,
  avatarSm,
  avatarMd,
  avatarLg,
  iconSm,
  iconMd,
  fadeHeight,
  channelHeaderHeight,
  borderWidth,
  avatarRingWidth,
}

const neriDimentDefaults = <NeriDimen, double>{
  NeriDimen.railWidth: 76,
  NeriDimen.listPaneWidth: 310,
  NeriDimen.controlSize: 40,
  NeriDimen.avatarXs: 20,
  NeriDimen.avatarSm: 45,
  NeriDimen.avatarMd: 58,
  NeriDimen.avatarLg: 73,
  NeriDimen.iconSm: 24,
  NeriDimen.iconMd: 30,
  NeriDimen.fadeHeight: 31,
  NeriDimen.channelHeaderHeight: 57,
  NeriDimen.borderWidth: 1,
  NeriDimen.avatarRingWidth: 1.5,
};
