import 'dart:convert';
import 'dart:io';

const _shortcodesOutput = 'lib/utils/emoji_shortcodes.dart';
const _catalogOutput = 'lib/utils/emoji_catalog.dart';
const _header = '// generated by tool/gen_emoji_shortcodes.dart, do not edit!!';

void main(List<String> args) {
  if (args.length != 1) {
    stderr.writeln(
      'Usage: dart run tool/gen_emoji_shortcodes.dart <nermity-web-vanilla/public/emoji.json>',
    );
    exit(64);
  }

  final emojis = (jsonDecode(File(args.single).readAsStringSync()) as List)
      .cast<Map<String, dynamic>>();

  _write(_shortcodesOutput, _shortcodes(emojis));
  _write(_catalogOutput, _catalog(emojis));
}

String _shortcodes(List<Map<String, dynamic>> emojis) {
  final shortcodes = <String, String>{
    for (final emoji in emojis)
      for (final name in (emoji['short_names'] as List).cast<String>())
        name: emoji['emoji'] as String,
  };

  final buffer = StringBuffer()
    ..writeln(_header)
    ..writeln()
    ..writeln('const emojiShortcodes = <String, String>{');
  for (final MapEntry(:key, :value) in shortcodes.entries) {
    buffer.writeln("  '${_escape(key)}': '${_escape(value)}',");
  }
  buffer.writeln('};');
  return buffer.toString();
}

String _catalog(List<Map<String, dynamic>> emojis) {
  final categories = <String, List<Map<String, dynamic>>>{};
  for (final emoji in emojis) {
    (categories[emoji['category'] as String] ??= []).add(emoji);
  }

  final buffer = StringBuffer()
    ..writeln(_header)
    ..writeln()
    ..writeln('typedef CatalogEmoji = ({String emoji, String name});')
    ..writeln()
    ..writeln('const emojiCatalog = <String, List<CatalogEmoji>>{');
  for (final MapEntry(key: category, value: members) in categories.entries) {
    buffer.writeln("  '${_escape(category)}': [");
    for (final emoji in members) {
      final name = (emoji['short_names'] as List).first as String;
      buffer.writeln(
        "    (emoji: '${_escape(emoji['emoji'] as String)}', "
        "name: '${_escape(name)}'),",
      );
    }
    buffer.writeln('  ],');
  }
  buffer.writeln('};');
  return buffer.toString();
}

void _write(String path, String contents) {
  File(path).writeAsStringSync(contents);
  Process.runSync('dart', ['format', path]);
}

String _escape(String input) => input.runes.map((rune) {
  if (rune < 0x20 || rune > 0x7e) return '\\u{${rune.toRadixString(16)}}';
  if (rune == 0x24 || rune == 0x27 || rune == 0x5c) {
    return '\\${String.fromCharCode(rune)}';
  }
  return String.fromCharCode(rune);
}).join();
