import 'dart:convert';
import 'dart:io';

const _output = 'lib/utils/emoji_shortcodes.dart';

void main(List<String> args) {
  if (args.length != 1) {
    stderr.writeln(
      'Usage: dart run tool/gen_emoji_shortcodes.dart <nermity-web/src/emoji/emoji.json>',
    );
    exit(64);
  }

  final emojis = jsonDecode(File(args.single).readAsStringSync()) as List;
  final shortcodes = <String, String>{
    for (final emoji in emojis.cast<Map<String, dynamic>>())
      for (final name in (emoji['short_names'] as List).cast<String>())
        name: emoji['emoji'] as String,
  };

  final buffer = StringBuffer()
    ..writeln('// generated by tool/gen_emoji_shortcodes.dart, do not edit!!')
    ..writeln()
    ..writeln('const emojiShortcodes = <String, String>{');
  for (final MapEntry(:key, :value) in shortcodes.entries) {
    buffer.writeln("  '${_escape(key)}': '${_escape(value)}',");
  }
  buffer.writeln('};');

  File(_output).writeAsStringSync(buffer.toString());
  Process.runSync('dart', ['format', _output]);
}

String _escape(String input) => input.runes.map((rune) {
  if (rune < 0x20 || rune > 0x7e) return '\\u{${rune.toRadixString(16)}}';
  if (rune == 0x24 || rune == 0x27 || rune == 0x5c) {
    return '\\${String.fromCharCode(rune)}';
  }
  return String.fromCharCode(rune);
}).join();
