name: Build Web (WASM)

on:
  push:
    branches: [main]

concurrency:
  group: build-web-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build Web (WASM)
        run: flutter build web --wasm

      - name: Zip The Build
        uses: vimtor/action-zip@v1
        with:
          files: build/web/
          dest: flutter-web.zip

      - name: Deploy to Server
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: "flutter-web.zip"
          remote: "/var/www/flutter-web.zip"
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}

      - name: Unzip built
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          port: ${{ secrets.PORT }}
          script: |
            unzip -o -DD /var/www/flutter-web.zip -d /var/www/flutter.nerimity.com
            rm -rf /var/www/flutter-web.zip
